version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - "3306:3306" # MySQL uses port 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8081:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}"
      - "SPRING_DATASOURCE_USERNAME=${MYSQL_USER}"
      - "SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}"
      - "JWT_ISSUER=${JWT_ISSUER}"
      - "SWAGGER_CONTACT_MAIL=${SWAGGER_CONTACT_MAIL}"
      - "SWAGGER_CONTACT_URL=${SWAGGER_CONTACT_URL}"
      - "SWAGGER_APP_NAME=${SWAGGER_APP_NAME}"
      - "SWAGGER_APP_VERSION=${SWAGGER_APP_VERSION}"
      - "SWAGGER_APP_LICENSE_URL=${SWAGGER_APP_LICENSE_URL}"
      - "SWAGGER_APP_LICENSE=${SWAGGER_APP_LICENSE}"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8082:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_PLUGINS=tables-filter tinymce
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
    driver: local
